- src/main/java/org/kuali/kra/subaward/subawardrule/SubAwardDocumentRule.java
84250170
Damien,
Please review the code change, and let me know if there is any change needed.   Thanks.
> [Finishes #84250170] subaward awardnumber req error

- pom.xml
- src/main/db/liquibase/kc_fix_changelog.xml
- src/main/db/liquibase/kc_fix_rice_changelog.xml
add liquibase to kc_fixes.  Note that your changeset must include comment on top where ## is the changeset number id.
-- changeset ekualiti:##-description
> [Finishes #85920158] add liquibase to kc_fixes

- src/main/resources/org/kuali/kra/irb/repository-irb.xml
- src/main/resources/repository.xml
Issue #34 / [Finishes 84890244]
> Issue #34 / [Finishes 84890244] replaced repository.xml and repository-irb.xml with KC 5.2.1 versions.

- src/main/java/org/kuali/kra/award/home/AwardService.java
- src/main/java/org/kuali/kra/award/home/AwardServiceImpl.java
- src/main/java/org/kuali/kra/award/paymentreports/awardreports/reporting/service/ReportTrackingNotificationServiceImpl.java
- src/main/java/org/kuali/kra/subaward/subawardrule/SubAwardDocumentRule.java
move getActiveOrNewestAward method to award service.  Fix foundation original method to better reflect actual function
> [Finishes #84603970] move getActiveOrNewestAward method to award service

- src/main/resources/org/kuali/kra/datadictionary/docs/RolodexMaintenanceDocument.xml
[Finishes #88157664] Committing a fix for address book maintenance document active to default as true.
> [Finishes #88157664] Committing a fix for address book maintenance document active to default as true.

- src/main/java/org/kuali/kra/budget/calculator/SalaryCalculator.java
budget personnel costs calculate amounts incorrectly when salary inflation applies with anniversary date
> Fixes #52 / [Finishes #86329522] budget personnel costs calculate amounts incorrectly when salary inflation applies with anniversary date

- src/main/java/org/kuali/kra/award/awardhierarchy/AwardHierarchyServiceImpl.java
award should copy over project obligated start end dates when copying new award
> Issue #58 / [Finishes #88287292] award should copy over project obligated start end dates when copying new award

- src/main/java/org/kuali/kra/award/printing/xmlstream/AwardNoticeXmlStream.java
award print does not display current values for award amount info
> [Finishes #89250412] award print does not display current values for award amount info

- src/main/java/org/kuali/kra/proposaldevelopment/web/struts/action/ProposalDevelopmentKeyPersonnelAction.java
Proposal Development: ERA Commons error causes exception STE when user tries to resolve
> Issue #66 / [Finishes #89663214] Proposal Development: ERA Commons error causes exception STE when user tries to resolve

- src/main/java/org/kuali/kra/award/home/Award.java
- src/main/java/org/kuali/kra/award/home/AwardServiceImpl.java
award t&m should not change update user on history panel for prior award versions
> [89656862] -Test- award t&m should not change update user on history panel for prior award versions

- src/main/java/org/kuali/kra/award/home/Award.java
- src/main/java/org/kuali/kra/award/home/AwardServiceImpl.java
Award T&M Should Not Change updateUser on History Panel for Prior Award Versions
> [89656862] -Staging- Award T&M Should Not Change updateUser on History Panel for Prior Award Versions #72

- src/main/java/org/kuali/kra/service/UnitService.java
- src/main/java/org/kuali/kra/service/impl/UnitServiceImpl.java
hide inactive unit numbers in unit hierarchy
> Issue #77 / [91135976] - TEST - hide inactive unit numbers in unit hierarchy

- src/main/java/org/kuali/kra/service/VersionHistoryService.java
- src/main/java/org/kuali/kra/service/impl/VersionHistoryServiceImpl.java
- src/main/java/org/kuali/kra/subaward/lookup/SubAwardLookupableHelperServiceImpl.java
Issue #76 / [Finishes #91136756] committing code for fix the SubAward lookup and return only the highest version sub awards.
> Issue #76 / [Finishes #91136756] - TEST - committing code for fix the SubAward lookup and return only the highest version sub awards.

- src/main/java/org/kuali/kra/service/impl/UnitServiceImpl.java
hide inactive unit numbers in unit hieararchy
> Issue #77 / [Finishes #91135976] - Test - hide inactive unit numbers in unit hieararchy

- src/main/java/org/kuali/kra/service/UnitService.java
- src/main/java/org/kuali/kra/service/impl/UnitServiceImpl.java
Issue #77 hide inactive unit numbers in unit hierarchy #78
> Issue #77 / [91135976] - STAGING - hide inactive unit numbers in unit hierarchy #78

- src/main/java/org/kuali/kra/service/VersionHistoryService.java
- src/main/java/org/kuali/kra/service/impl/VersionHistoryServiceImpl.java
- src/main/java/org/kuali/kra/subaward/lookup/SubAwardLookupableHelperServiceImpl.java
Issue #76 / [Finishes #91136756] - TEST - committing code for fix the SubAward lookup and return only the highest version sub awards. #81.
> Issue #76 / [Finishes #91136756] - STAGING - committing code for fix the SubAward lookup and return only the highest version sub awards. #81

- src/main/webapp/WEB-INF/tags/award/awardSubaward.tag
Issue #80 / [Finishes #91135264] - STAGING - enabling the edit button to show on the subaward document. #83
> Issue #80 / [Finishes #91135264] - STAGING - enabling the edit button to show on the subaward document. #83

- src/main/webapp/scripts/awardHierarchyTimeAndMoney.js
Issue #86 / [Finishes #90739704] - TEST - committing code to fix the issue with time and money document adding unnecessary transactions.
> Issue #86 / [Finishes #90739704] - TEST - committing code to fix the issue with time and money document adding unnecessary transactions.

- src/main/java/org/kuali/kra/award/web/struts/action/AwardAction.java
Issue #101 / [Finishes #92147692] - TEST - Adding comments to the code and fixing file version in KC-fixes and EKC.
> Issue #101 / [Finishes #92147692] - TEST - Adding comments to the code and fixing file version in KC-fixes and EKC.

- src/main/db/liquibase/kc_vt_88346510_add_table_comm_schedule_attachment_id.sql
- src/main/db/liquibase/kc_vt_changelog.xml
- src/main/java/org/kuali/kra/common/committee/meeting/CommitteeScheduleAttachmentsBase.java
- src/main/java/org/kuali/kra/common/committee/meeting/MeetingActionBase.java
- src/main/java/org/kuali/kra/common/committee/meeting/MeetingActionsActionBase.java
- src/main/java/org/kuali/kra/common/committee/meeting/MeetingFormBase.java
- src/main/java/org/kuali/kra/iacuc/committee/meeting/IacucMeetingActionsAction.java
- src/main/java/org/kuali/kra/meeting/MeetingActionsAction.java
> Fixes #96 / [Finishes #88346510] - Staging - Extending functionality of IRB and IACUC meetings #97

- src/main/java/org/kuali/kra/award/web/struts/action/AwardAction.java
Issue #101 / [Finishes #92147692] - STAGING - Adding comments to the code and fixing file version in KC-fixes and EKC. #102
> Issue #101 / [Finishes #92147692] - STAGING - Adding comments to the code and fixing file version in KC-fixes and EKC. #102

- src/main/java/org/kuali/kra/coi/notesandattachments/attachments/FinancialEntityAttachment.java
> Issue #95 / [Finishes #90923978] - Staging - coi financial entity attachments #90

- src/main/java/org/kuali/kra/dao/ojb/AwardLookupDaoOjb.java
> Issue #104 / [Finishes #91196844] - Staging - Award - Award Hierarchy cancelled document in lookup #105

- src/main/db/liquibase/kc_vt_93134154_increase_comments_to_match_datadictionary.sql
- src/main/db/liquibase/kc_vt_changelog_nobase.xml
subaward comment exceeding character limit crash
> [Finishes #93134154] -TEST- subaward comment exceeding character limit crash

- src/main/java/org/kuali/kra/subaward/bo/SubAward.java
project people in Award are unable to open Negotiation when the association type is Subaward
> Issue #110 / [Finishes #92539878] -TEST- project people in Award are unable to open Negotiation when the association type is Subaward

- src/main/java/org/kuali/kra/proposaldevelopment/rules/ProposalDevelopmentProposalAttachmentsAuditRule.java
Proposal: stack trace error looking up sponsor when validations are on
> Issue #116 / [Finishes #93063014] -TEST- Proposal: stack trace error looking up sponsor when validations are on

- src/main/java/org/kuali/kra/subaward/web/struts/action/SubAwardAction.java
- src/main/java/org/kuali/kra/subaward/web/struts/action/SubAwardHomeAction.java
Issue #119 subaward fdp agreement print crashes after reload
> Issue #119 / [Finishes #93572340] -TEST- subaward fdp agreement print crashes after reload

- src/main/db/liquibase/kc_vt_93134154_increase_comments_to_match_datadictionary.sql
- src/main/db/liquibase/kc_vt_changelog_nobase.xml
Comments exceeding character limit crash in 3 places - link to TEST #107
> [Finishes #93134154] -STAGING- Comments exceeding character limit crash in 3 places

- src/main/java/org/kuali/kra/subaward/bo/SubAward.java
project people in Award are unable to open Negotiation when the association type is Subaward - Link to test #111
> Issue #110 / [Finishes #92539878] -STAGING- project people in Award are unable to open Negotiation when the association type is Subaward

- src/main/java/org/kuali/kra/proposaldevelopment/rules/ProposalDevelopmentProposalAttachmentsAuditRule.java
Proposal: stack trace error looking up sponsor when validations are on - Link to test #117
> Issue #116 / [Finishes #93063014] -STAGING- Proposal: stack trace error looking up sponsor when validations are on

- src/main/java/org/kuali/kra/subaward/web/struts/action/SubAwardAction.java
- src/main/java/org/kuali/kra/subaward/web/struts/action/SubAwardHomeAction.java
subaward fdp agreement print crashes after reload  - Link to test commit #120
> Issue #119 / [Finishes #93572340] -STAGING- subaward fdp agreement print crashes after reload 

- src/main/java/org/kuali/kra/infrastructure/Constants.java
- src/main/webapp/WEB-INF/tags/subaward/subAwardHistoryOfChanges.tag
> Issue #147 / [Finishes #90315372] - TEST - subaward warning messages not appearing #148

- src/main/webapp/scripts/awardHierarchyTimeAndMoney.js
Issue #86 / [Finishes #90739704] - STAGING - committing code to fix the issue with time and money document adding unnecessary transactions. #99
> Issue #86 / [Finishes #90739704] - STAGING - committing code to fix the issue with time and money document adding unnecessary transactions. #99

- src/main/webapp/WEB-INF/jsp/proposaldevelopment/ProposalDevelopmentApproverView.jsp
- src/main/webapp/WEB-INF/tags/summary/proposalSummaryYnq.tag
contribution from kracoeus-7154
> Issue #131 / [Finishes #89555618] - STAGING - display old style YNQ in PD summary tab

- src/main/java/org/kuali/kra/award/paymentreports/awardreports/AwardReportTermRuleImpl.java
- src/main/resources/org/kuali/kra/datadictionary/AwardReportTerm.xml
frequent base as required fields
> Issue #134 / [Finishes #89309222] - STAGING - validated award report frequency code and frequent base as required fields

- src/main/java/org/kuali/kra/proposaldevelopment/web/struts/action/ProposalDevelopmentAbstractsAttachmentsAction.java
> Issue #137 / [Finishes #90736860] - STAGING - only have notification dialog for attachment change when enroute

- src/main/java/org/kuali/kra/award/paymentreports/awardreports/reporting/service/ReportTrackingServiceImpl.java
> [kc_fixes] Issue #156 /  [Finishes #95194040] TEST - Some reports are missing on Award documents.

- src/main/java/org/kuali/kra/iacuc/onlinereview/IacucProtocolOnlineReviewAction.java
> Issue #159 / [Finishes #95207940] - TEST - Fixing edit mode check for private/final flags #160

- src/main/resources/org/kuali/kra/award/AwardSpringBeans.xml
> [kc_fixes] [Finishes #93226128] TEST remove baseDate from group by attributes.

- src/main/java/org/kuali/kra/service/impl/SponsorServiceImpl.java
This NPE bug affected #93042556.
> Issue #87 / [Finishes #91531064] - TEST - fix NPE

- src/main/java/org/kuali/kra/infrastructure/Constants.java
- src/main/java/org/kuali/kra/infrastructure/KeyConstants.java
- src/main/java/org/kuali/kra/institutionalproposal/rules/InstitutionalProposalDocumentRule.java
- src/main/java/org/kuali/kra/proposaldevelopment/rules/ProposalDevelopmentDocumentRule.java
- src/main/java/org/kuali/kra/proposaldevelopment/rules/ProposalDevelopmentProposalRequiredFieldsAuditRule.java
- src/main/java/org/kuali/kra/proposaldevelopment/rules/ProposalDevelopmentSponsorProgramInformationAuditRule.java
- src/main/java/org/kuali/kra/service/impl/SponsorServiceImpl.java
- src/main/resources/ApplicationResources.properties
- src/main/resources/org/kuali/kra/datadictionary/Sponsor.xml
- src/main/resources/org/kuali/kra/datadictionary/docs/SponsorMaintenanceDocument.xml
- src/main/webapp/WEB-INF/tags/institutionalproposal/institutionalProposalSponsorAndProgramInformation.tag
- src/main/webapp/WEB-INF/tags/proposaldevelopment/proposalDevelopmentRequiredFields.tag
Issue #87 / [Finishes #91531064] - STAGING - enabling to edit the Institutional proposal when the sponsor is inactive. #88 #94
> Issue #87 / [Finishes #91531064] - STAGING - enabling to edit the Institutional proposal when the sponsor is inactive. #88 #94

- src/main/java/org/kuali/kra/award/paymentreports/awardreports/reporting/service/ReportTrackingServiceImpl.java
> Issue #156 /  [Finishes #95194040] - STAGING - Some reports are missing on Award documents. #157

- src/main/resources/org/kuali/kra/award/AwardSpringBeans.xml
> [kc_fixes] [Finishes #93226128] - STAGING - remove baseDate from group by attributes.

- src/main/java/org/kuali/kra/institutionalproposal/service/impl/InstitutionalProposalLookupableHelperServiceImpl.java
> Issue #181 / [Finishes #95893798] - TEST - Adding public get methods for class services #182

- src/main/java/org/kuali/kra/award/document/AwardDocument.java
- src/main/java/org/kuali/kra/award/web/struts/action/AwardAction.java
EKC-1351
Roll back code changes for report generation process when Award goes to Final
> [kc_fixes] EKC-1351 - TEST - Award-Report-Tracking-Canceled-Award

- src/main/java/org/kuali/kra/proposaldevelopment/web/struts/action/ProposalDevelopmentActionsAction.java
> Issue #123 / EKC-1323 - STAGING - #stage not allow initiator to approve PD without certification
